# Generated by Django 5.1.3 on 2024-12-12 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_subcategory_main_category_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=35)),
                ('value', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('alt', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=20)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.feature')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('meta_title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('short_description', models.TextField()),
                ('full_description', models.TextField()),
                ('meta_description', models.TextField()),
                ('product_code', models.CharField(max_length=50)),
                ('item', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=50)),
                ('off_price', models.CharField(blank=True, max_length=50, null=True)),
                ('discount', models.CharField(blank=True, max_length=2, null=True)),
                ('published', models.BooleanField(default=False)),
                ('stock', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('max_order', models.CharField(max_length=5)),
                ('items', models.ManyToManyField(related_name='product_items', to='products.items')),
                ('main_category', models.ForeignKey(default='دسته بندی نشده', on_delete=django.db.models.deletion.SET_DEFAULT, to='products.maincategory')),
                ('sub_category', models.ForeignKey(blank=True, default='دسته بندی نشده', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.subcategory')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.uploadimage')),
                ('images', models.ManyToManyField(related_name='product_images', to='products.uploadimage')),
            ],
        ),
    ]
