# Generated by Django 5.1.3 on 2024-12-12 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_feature_uploadimage_items_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
