# Generated by Django 5.1.3 on 2024-12-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_items_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='value',
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
