# Generated by Django 5.1.3 on 2024-12-13 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_color_size_remove_product_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, max_length=50, null=True)),
                ('has_color', models.BooleanField(default=False)),
                ('colors', models.CharField(blank=True, choices=[], max_length=15, null=True)),
                ('has_size', models.BooleanField(default=False)),
                ('sizes', models.CharField(blank=True, choices=[], max_length=15, null=True)),
                ('stock', models.CharField(max_length=5)),
                ('price', models.CharField(max_length=10)),
                ('discount', models.BooleanField(default=False)),
                ('off_price', models.CharField(blank=True, max_length=10, null=True)),
                ('discount_percent', models.CharField(blank=True, max_length=2, null=True)),
                ('weight', models.CharField(max_length=50)),
                ('max_order', models.CharField(max_length=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variety', to='products.product')),
            ],
        ),
    ]
