# Generated by Django 5.1.3 on 2024-12-13 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productvariety'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='color_name',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='size',
            old_name='size_name',
            new_name='size',
        ),
        migrations.DeleteModel(
            name='ProductVariety',
        ),
    ]
