# Generated by Django 5.1.3 on 2024-12-14 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_category_main_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maincategory',
            old_name='name',
            new_name='main_name',
        ),
        migrations.RenameField(
            model_name='maincategory',
            old_name='slug',
            new_name='main_slug',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='name',
            new_name='sub_name',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='slug',
            new_name='sub_slug',
        ),
    ]
