# Generated by Django 5.1.3 on 2024-12-15 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_rename_name_maincategory_main_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sub_category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.subcategory'),
        ),
    ]
